config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000

  root 'cars#index'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete '/logout',
         to: 'sessions#destroy'
  get 'verification/:token', to: 'users#verify', as: 'verify_email'

  resources :cars

  resources :users,
    only: [:new, :create],
    path_names: { new: 'signup' }

end

app/models/student.rb
class Student < ActiveRecord::Base
  def self.seed_data!
    ages = (5..18).to_a
    heights = {
      5  => (40..46).to_a,
      6  => (42..49).to_a,
      7  => (44..52).to_a,
      8  => (47..54).to_a,
      9  => (49..57).to_a,
      10 => (50..59).to_a,
      11 => (52..61).to_a,
      12 => (54..64).to_a,
      13 => (56..66).to_a,
      14 => (59..70).to_a,
      15 => (62..72).to_a,
      16 => (63..73).to_a,
      17 => (64..74).to_a,
      18 => (65..75).to_a,
    }
    500.times do |number|
      age = ages.sample
      date_of_birth = (age).years.ago + rand(11).months + rand(30).days
      height = heights[age].sample
      Student.create(
        :first_name => Faker::Name.first_name,
        :middle_name => Faker::Name.first_name,
        :last_name => Faker::Name.last_name,
        :date_of_birth => date_of_birth,
        :hair_color => ['red', 'brown', 'black', 'blonde'].sample,
        :eye_color => ['blue', 'green', 'brown'].sample,
        :height => height,
        :weight => random_weight_for_height(height),
        :sex => ['M', 'F'].sample
      )
    end
  end

  private

  def self.random_weight_for_height(height)
    bmi = (19..40).to_a.sample
    sprintf("%.2f", ((height * height) * bmi)/703)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  def needs_verification!
    update_attributes!(
      token: SecureRandom.urlsafe_base64,
      verified_email: false
    )
    UserNotifier.signed_up(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:edit, :update]

  def index
    @cars = Car.all.paginate(:page => params[:page], per_page:10)
  end

  def edit
  end

  def update
    @car.update(car_params)
    redirect_to cars_path,
      notice: "#{@car.year} #{@car.make} #{@car.model} updated"
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.save
    redirect_to cars_path,
      notice: "#{@car.year} #{@car.make} #{@car.model} created"
  end

  # def destroy
  #   @car.destroy
  #   respond_to do |format|
  #     format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end


  private

  def car_params
    params.require(:car).permit(:year, :make, :model, :price)
  end

  def find_car
    @car = Car.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      # valid login/password
      session[:id] = user.id
      redirect_to root_path,
                  notice: "Welcome back #{user.first_name.titleize}"
    else
      # invalid login or password
      flash[:error] = 'Invalid email or password'
      render :login
    end
  end

  def destroy
    if user = current_user
      session[:id] = nil
      redirect_to root_path,
      notice: "#{user.email} has been logged out."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.needs_verification!
      session[:id] = @user.id
      redirect_to root_path,
        notice: "Thank you for signing up #{@user.first_name.titlecase}"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email,
      :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |form| %>
  <p>
    <%= form.label :make %>
    <%= form.text_field :make %>
  </p>
  <p>
    <%= form.label :model %>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :year %>
    <%= form.text_field :year %>
  </p>
  <p>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render 'form' %>

app/views/cars/index.html.erb
<h1>Cars</h1>
<%= will_paginate @cars, renderer: BootstrapPagination::Rails %>
<table id='my_cars' class="table table-striped">
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Price</th>
  </tr>

  <% @cars.each do |car| %>
    <tr>
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= number_to_currency(car.price, precision: 0) %></td>
      <td><%= link_to('Edit', edit_car_path(car)) %></td>
      <!--<td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
</table>
<%= will_paginate @cars, renderer: BootstrapPagination::Rails %>
<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render 'form' %>

app/views/layouts/_authentication.html.erb
<% if current_user %>
  Signed in as <%= current_user.email %>
  <%= link_to 'Logout', logout_path, method: :delete %>
  <% else %>
<%= link_to 'Signup', new_user_path %>
<%= link_to 'Login', login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= render 'layouts/authentication' %>
<%= yield %>

</body>
</html>

app/views/user_notifier/signed_up.html.erb
Hello <%= @user.first_name.titleize %>,

You recently created a <%= t('site_name') %> account
using your email address of <%= @user.email %>.

To verify your email address, please open the following link:

<a href="<%= verify_email_url(@user.token)%>">Click Here</a>

If the link does not work, please login to your account
and enter this token:

<%= @user.token %>

Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/signed_up.text.erb
Hello <%= @user.first_name.titleize %>,

You recently updated your <%= t('site_name') %> account's
email address to <%= @user.email %>.

To verify your email address, please open the following link:

<%= verify_email_url(@user.token) %>

If the link does not work, please login to your account
and enter this token:

<%= @user.token %>

Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/verified.html.erb
Hello <%= @user.first_name.titleize %>,

You recently created a <%= t('site_name') %> account
using your email address of <%= @user.email %>.

To verify your email address, please open the following link:

<a href="<%= verify_email_url(@user.token)%>">Click Here</a>

If the link does not work, please login to your account
and enter this token:

<%= @user.token %>

Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/verified.text.erb
Hello <%= @user.first_name.titleize %>,

Thank you for updating your email address to <%= @user.email %>.
Your email address has been verified in our system.

Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/verify.html.erb
<h1>UserNotifier#verify</h1>

<p>
  <%= @greeting %>, find me in app/views/user_notifier/verify.html.erb
</p>

app/views/user_notifier/verify.text.erb
Hello <%= @user.first_name.titleize %>,

You recently created a <%= t('site_name') %> account
using your email address of <%= @user.email %>.

To verify your email address, please open the following link:

<%= verify_email_url(@user.token) %>

If the link does not work, please login to your account
and enter this token:

<%= @user.token %>

Thank you for visiting <%= t('site_name') %>.

app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>
  <p>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </p>
  <p>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation, 'Password Confirmation' %>
    <%= form.password_field :password_confirmation %>
  </p>
  <p>
    <%= form.submit 'Signup' %>
  </p>
<% end %>

app/views/users/new.html.erb
<h2>Signup</h2>

<%= render 'form' %>